#!/bin/bash

set -eu

ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
cd $ROOT

./npm-hyperinstall "$@"

pushd ../dev/xdl
npm run build
npm unlink || true
npm link
popd

pushd ../expo/tools-public
npm link xdl
popd

cd ../expo/js/__develop__
exp start
